//
//  NewsInteractor.swift
//  swift-clean-arch
//
//  Created by Admin on 30/09/2019.
//  Copyright (c) 2019 Vladlin Moiseenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import AlamofireObjectMapper

protocol NewsListBusinessLogic {
    func fetchNews()
}

class NewsListInteractor: NewsListBusinessLogic {
    
    var presenter: NewsListPresentationLogic?
    var newsFetcher: NewsFetcherType?
    
    func fetchNews() {
   
        newsFetcher?.fetchNews(completion: { [weak self] news in
            if let news = news {
                self?.presenter?.passNews(news: news)
            }
        })
        
    }
}
