//
//  NewsModels.swift
//  swift-clean-arch
//
//  Created by Admin on 30/09/2019.
//  Copyright (c) 2019 Vladlin Moiseenko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

class NewsRequestResponse: Mappable {
    var title: String!
    var author: String!
    var description: String!
    var urlToImage: String!
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
       title <- map["title"]
       author <- map["author"]
       description <- map["description"]
       urlToImage <- map["urlToImage"]
    }
}
